core/urls.py
from django.urls import path, include
#from rest_framework import routers
from . import views

#router = routers.DefaultRouter()
#router.register(r'brands', views.BrandViewSet)

urlpatterns = [
    path('', views.empty, name='empty'),
    # HTML
    #path('', views.main, name='main'),
    path('japan/', views.cars_catalog, name='japan'),








    #path('korea/', , name='korea'),

    # API
    #path('', include(router.urls)),
    #path('cars/', views.CarsCatalog.as_view(), name='cars'),
    #path('brands/<int:brand__id>/models/', views.CarsModel.as_view(), name='car_models')
]

feedback/urls.py
from django.urls import path
from .views import feedback_view


urlpatterns = [
    path('', feedback_view, name='feedback_form'),
]

webbin/urls.py
from django.shortcuts import render
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('feedback/', include('feedback.urls')),
    path('success/', lambda request: render(request, 'success.html'), name='success'),

    path('api/', include('core.urls')),
]

feedback/models.py
from django.db import models



class Feedback(models.Model):
    name = models.CharField(max_length=20, verbose_name="Имя")
    phone_number = models.CharField(max_length=16, verbose_name="Телефон")
    content = models.TextField(max_length=200, verbose_name="Сообщение")
    privacy_policy_agreed = models.BooleanField(default=False, verbose_name="Согласие с политикой конфиденциальности")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата отправки")

    def __str__(self):
        return f"{self.name} ({self.phone_number})"

feedback/forms.py
from django import forms
from .models import Feedback

class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ['name', 'phone_number', 'content', 'privacy_policy_agreed']

        widgets = {
            'name': forms.TextInput(attrs={
                'placeholder': 'Введите имя',
                'pattern': '^[A-Za-zА-Яа-яЁё\s]+$',
                'title': 'Имя должно содержать только буквы и пробелы.',
                'maxlength': '20',
                'required': True,
            }),
            'phone_number': forms.TextInput(attrs={
                'placeholder': '+7',
                'pattern': r'^\+7 [0-6,9]\d{2} \d{3} \d{2} \d{2}$',
                'title': "Формат: '+7 999 999 99 99'",
                'maxlength': '16',
                'required': True,
            }),
            'content': forms.Textarea(attrs={
                'placeholder': 'Введите текст сообщения, укажите страну, марку и год машины.',
                'maxlength': '200',
                'rows': 10,
                'cols': 40,
            }),
            'privacy_policy_agreed': forms.CheckboxInput(attrs={
                'required': True,
            }),
        }

feedback/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import FeedbackForm

def feedback_view(request):
    if request.method == "POST":
        form = FeedbackForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/success/')  # Переход на страницу успеха
    else:
        form = FeedbackForm()

    return render(request, 'feedback/feedback_form.html', {'form': form})

feedback/templates/feedback/feedback_form.html
<form class="contact_form" id="contactForm" method="post" action="">
    {% csrf_token %}
    <div class="form_group">
        <label for="id_name">
            <p>Имя</p>
            {{ form.name }}
        </label>
        <label for="id_phone_number">
            <p>Телефон</p>
            {{ form.phone_number }}
        </label>
    </div>
    <div class="form_group">
        <label for="id_content">
            <p>Уточните свой вопрос</p>
            {{ form.content }}
        </label>
    </div>
    <div class="form_group">
        <label for="id_privacy_policy_agreed">
            <span class="checkmark"></span>
            {{ form.privacy_policy_agreed }}
            <p>С <a target="_blank" href="/static/files/privacy_policy.pdf">правилами политики конфиденциальности</a> ознакомлен</p>
        </label>
    </div>
    <div class="form_group">
        <button type="submit" name="submit">Отправить</button>
    </div>
</form>